import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, paddingHorizontal: 20 },
  header: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingTop: 50, paddingBottom: 15, borderBottomWidth: 1, marginBottom: 10 },
  title: { fontSize: 24, fontWeight: '900' },
  statusText: { fontSize: 14, textAlign: 'center', fontWeight: '500' },
  connectContainer: { width: '100%', alignItems: 'center' },
  scanBtn: { width: '100%', padding: 18, borderRadius: 12, alignItems: 'center' },
  scanBtnText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  manualInputRow: { flexDirection: 'row', width: '100%', marginTop: 20 },
  ipInput: { flex: 1, padding: 15, borderRadius: 12, marginRight: 10 },
  connectBtn: { paddingHorizontal: 20, borderRadius: 12, justifyContent: 'center' },
  connectBtnText: { color: 'white', fontWeight: 'bold' },
  pcBox: { width: '100%', padding: 20, borderRadius: 16, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 },
  pcName: { fontSize: 16, fontWeight: 'bold' },
  pcIp: { fontSize: 12, marginTop: 4 },
  fileArea: { flex: 1, paddingTop: 20 },
  uploadBtn: { padding: 18, borderRadius: 12, alignItems: 'center', marginTop: 20 },
  uploadBtnText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  progressCard: { padding: 20, borderRadius: 16, marginBottom: 10 },
  progressHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  progressCount: { fontWeight: 'bold' },
  progressSpeed: { fontWeight: 'bold' },
  progressBarBg: { height: 8, borderRadius: 4, overflow: 'hidden' },
  progressBarFill: { height: '100%', borderRadius: 4 },
  modalContainer: { flex: 1, paddingHorizontal: 20, paddingTop: 60 },
  modalTitle: { fontSize: 22, fontWeight: 'bold', textAlign: 'center' },
  modalSubtitle: { fontSize: 14, textAlign: 'center', marginBottom: 20 },
  visualizerList: { flex: 1 },
  visualizerRow: { flexDirection: 'row', padding: 18, alignItems: 'center', borderRadius: 12, marginBottom: 8 },
  checkbox: { marginRight: 15 },
  visualizerFileDetails: { flex: 1 },
  visualizerFileName: { fontSize: 14, fontWeight: '600' },
  visualizerFileSize: { fontSize: 12, marginTop: 4 },
  modalButtons: { flexDirection: 'row', paddingVertical: 20, justifyContent: 'space-between' },
  modalBtn: { flex: 1, padding: 16, borderRadius: 12, alignItems: 'center', marginHorizontal: 5 },
  modalBtnText: { color: 'white', fontSize: 16, fontWeight: 'bold' }
});